
server:
  port: 8761

spring:
  application:
    name: erwin-eureka

eureka:
  client:
    # 注册自身到eureka服务器
    register-with-eureka: false
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false
  server:
    # 关闭自我保护模式
    enable-self-preservation: false